### ISSUE TITLE
Logs for crashing

### ISSUE THREAD

**Issue by Tellik** [aki-art/ONI-Mods#19] opened 2022-10-07 02:56 UTC
Saw that you were asking for logs in the steam comments, so I wanted to provide mine as well. If you need any other information, let me know.

OS: Linux 64 Bit
Game Version: 526233
Mod Version: 1.0.4.0

[Player Log](https://pastebin.com/Gpb2b3xN)

**Comment by aki-art** [comment] 2022-10-07 04:55
Duplicate of #16

**Comment by aki-art** [comment] 2022-10-17 09:13
Fixed in 1.0.8, now live on Steam.

**Closed by aki-art** 2022-10-17 09:13 UTC
